# Site settings
title: Blog
header-img: img/home-radio.jpg
email: jdbailliestrong_at_gmail.com
description: "Thoughts, hacks, ideas and stories"
baseurl: "/blog"
url: "http://jonbstrong.com/blog"
twitter_username: jonbstrong
github_username:  jonbstrong
facebook_username:  jdbstrong

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
